config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  resources :games
  get '/snowboard', to: 'pages#snowboard'
  get 'current_user', to: "games#get_current_user"

  mount ActionCable.server => '/cable'

  post '/games/random', to: 'games#random_game', as: 'random'

  post '/games/:id/invite', to: 'games#invite', as: 'invite'
  delete '/games/:id/uninvite', to: 'games#uninvite', as: 'uninvite'

  post '/games/:id/send_invites', to: 'games#send_invites', as: 'send_invites'
  post '/games/:id/join', to: 'games#join', as: 'join'

  post '/games/:id/actions', to: 'games#actions', as: 'actions'
  delete '/games/:id/cancel_action', to: 'games#cancel_action', as: 'cancel_action'
  post '/games/:id/timer_update', to: 'games#timer_update', as: 'timer_update'
  post '/games/:id/map', to: 'games#map', as: 'map'
  post '/games/:id/get_invite_token', to: 'games#get_invite_token', as: 'get_invite_token'

  post '/read', to: 'messages#read', as: 'read'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord

  belongs_to :creator, class_name: 'User'
  has_many :players, dependent: :destroy
  has_many :users, through: :players
  has_and_belongs_to_many :invitees, class_name: 'User', join_table: 'game_invites_invitees', 
  						  association_foreign_key: 'game_invite_id', foreign_key: 'invitee_id'
  
  serialize :cities
  serialize :us_army_forces
  serialize :rebels_forces
  serialize :launch_sites

  scope :created_by, ->(user) { where(creator_id: user) }
  scope :not_created_by, ->(user) { where.not(creator_id: user) }
  scope :pending, -> { where(status: "pending") }
  scope :ongoing, -> { where(status: "ongoing") }
  scope :not_finished, -> { where.not(status: "finished") }

  def to_param
  	obfuscated_id = Hashids.new("l'art de la guerre", 8)
  	obfuscated_id.encode(id)
  end

end

app/helpers/games_helper.rb
module GamesHelper
  include GameInitializerHelper
  
  TIMER_START = 60

  def create_random_token
    SecureRandom.urlsafe_base64
  end 
  
  def random_game_available?
  	Game.created_by(User.find(1)).pending.empty?
  end

  def join_random_game(user)
  	game = Game.created_by(User.find(1)).pending.first

  	if game.players.where(user_id: user.id).empty?
  		Player.create(game_id: game.id, user_id: user.id, 
                    username: User.find(user.id).username, status:'pending_action')
  	else
  		flash[:danger] = 'You are already part of a random game'
  	end

    ready_to_start?(game)

  	return game
  end

  def create_random_game(user)
  	game = Game.create(creator_id: 1, status: "pending")
  	Player.create(game_id: game.id, user_id: user.id, 
                  username: User.find(user.id).username, status:'pending_action')
  	return game
  end

  def render_partial_for(type)
    statuses = ["invite_friends","pending","ongoing","updated"]
    status = statuses.include?(type) ? type : 'default'
    render "games/templates/#{status}" and return
  end

  def ready_to_start?(game)
    if game.players.size == 3
      game.update(status: "ongoing")
      get_started(game)
    end
  end

  def get_started(game)
    #A nation should be attributed to each player, and the country specific attributes are populated
    countries = [:china, :europe, :russia]
    game.players.shuffle.map.with_index do |player, i|
      player.update(country: countries[i], lost_cities: 0, lost_launch_sites: 0, 
                    launch_sites: LAUNCH_SITES_INITIALIZER[countries[i]], 
                    available_forces: FORCES_INITIALIZER[countries[i]], 
                    engaged_forces: {aircrafts: 0, tanks: 0}, 
                    spies: SPIES_INITIALIZER[countries[i]], 
                    winner: nil,
                    timer: TIMER_START)
    end

    #Trump location is randomized
    trump_location = rand(25)
    puts trump_location
    counter = 0
    cities = CITIES_INITIALIZER

    #cities are initialised and saved as a game attribute
    cities.each do |city, properties|
      if counter == trump_location
        properties[:trump] = true
      else 
        properties[:trump] = false
      end
      properties[:id] = counter
      properties[:spies] = {}
      properties[:destroyed] = false
      properties[:destroyed_by] = []
      properties[:conquered] = false
      counter += 1
    end
    game.update(turn_number: 1, cities: cities, us_army_forces: US_FORCES[:us_army], rebels_forces: REBELS_FORCES[:rebels], launch_sites: US_LAUNCH_SITES[:usa])
  end
  
  def get_missionable_cities(game, player)
    missionable_cities = {}
    game.cities.each do |city,properties|
      if !properties[:destroyed] && !properties[:conquered] && !properties[:spies].include?(player.country)
        missionable_cities[city] = {id: properties[:id]}
      end
    end
    return missionable_cities
  end

  def get_attackable_cities(game)
    attackable_cities = {}
    game.cities.each do |city,properties|
      if !properties[:destroyed] && !properties[:conquered]
        attackable_cities[city] = {id: properties[:id]}
      end
    end

    game.launch_sites.each do |site, properties|
      if properties[:operational]
        attackable_cities[site] = {id: properties[:id]}
      end
    end 
    return attackable_cities
  end 
  
  def reinforcements_for(player)
    reinforcements = {aircrafts: 0, tanks: 0}
    if player.country.to_sym == :europe
      reinforcements[:aircrafts] = FORCES_INITIALIZER[player.country.to_sym][:aircrafts] / 4
      reinforcements[:tanks] = FORCES_INITIALIZER[player.country.to_sym][:tanks] / 4
    else
      reinforcements[:aircrafts] = FORCES_INITIALIZER[player.country.to_sym][:aircrafts] / 6
      reinforcements[:tanks] = FORCES_INITIALIZER[player.country.to_sym][:tanks] / 6
    end
    return reinforcements
  end

  def next_turn(game)

    game.turn_number += 1
    trump_city = ''
    killed_spies = {china: [], europe: [], russia: []}
    
    game.cities.select{ |k,v| 
      if v[:trump]
        trump_city = k
      end
    }

    casualties_caused = {rebels: 0.09, us_army: 0.03}

    #REBELLION MANAGEMENT -------------------------------------------------------------------------
    rebels_power = power_computer game.rebels_forces
    us_army_power = power_computer game.us_army_forces

    game.rebels_forces.each do |type, firepower|
      game.rebels_forces[type] = ((1.0 - casualties_caused[:us_army]) * firepower).round
    end

    game.us_army_forces.each do |type, firepower|
      game.us_army_forces[type] = ((1.0 - casualties_caused[:rebels]) * firepower).round
    end

    possible_conquests = cities_to_be_conquered(game)
    conquered_this_turn = []

    if rebels_power > 0.5 * (rebels_power + us_army_power) && rebels_power <= 0.6 * (rebels_power + us_army_power)
      1.times do 
        conquered = possible_conquests.slice!(0)
        game.cities[conquered][:conquered] = true
        conquered_this_turn << conquered.to_s.humanize.capitalize
      end
    elsif rebels_power > 0.6 * (rebels_power + us_army_power) && rebels_power <= 0.8 * (rebels_power + us_army_power)
      2.times do 
        conquered = possible_conquests.slice!(0)
        game.cities[conquered][:conquered] = true
        conquered_this_turn << conquered.to_s.humanize.capitalize
      end
    elsif rebels_power > 0.8 * (rebels_power + us_army_power) 
      3.times do 
        conquered = possible_conquests.slice!(0)
        game.cities[conquered][:conquered] = true
        conquered_this_turn << conquered.to_s.humanize.capitalize
      end
    end

    if !conquered_this_turn.empty?
      conquered_this_turn = conquered_this_turn.join(', ')

      game.players.each do |player|
        Message.create(player_id: player.id, read: false, 
                       content:"#{conquered_this_turn} were conquered by the rebels and their allies during the last turn",
                       turn_number: game.turn_number)
      end 
    end
    
    #SPIES MANAGEMENT -----------------------------------------------------------------------------
    if !game.cities[trump_city][:spies].empty? && rand_comparator?(0.7)

      game.cities[trump_city][:spies].each do |country, spy_name|
        player = game.players.find_by(country: country)
        if rand_comparator?(0.3)
          
          killed_spies[country] << spy_name
          game.cities[trump_city][:spies].delete(country)

          Message.create(player_id: player.id, read: false, 
                         content:"#{spy_name} was killed after having found Trump in #{trump_city}, and Trump moved to another city",
                         turn_number: game.turn_number)
        else 
          Message.create(player_id: player.id, read: false, 
                         content:"#{spy_name} found Trump in #{trump_city}, but Trump escaped!",
                         turn_number: game.turn_number)
        end

      end

      trump_moves(game)

    elsif game.cities[trump_city][:spies].empty? && game.turn_number % 3 == 1

      trump_moves(game)

    else

      game.cities[trump_city][:spies].each do |country, spy_name|
        player = game.players.find_by(country: country)
        Message.create(player_id: player.id, read: false, 
                       content:"#{spy_name} located Trump in #{trump_city}, don't let him escape!!",
                       turn_number: game.turn_number)
    
      end 

    end

    #SPIES RISK -----------------------------------------------------------------------------------
    
    spies_on_mission = get_spies_on_mission(game)

    spies_on_mission.each do |country, array_of_spies|
      player = game.players.find_by(country: country)
      array_of_spies.each do |spy_hash|
        
        if game.cities[spy_hash[:city]][:destroyed]

          game.cities[spy_hash[:city]][:spies].delete(country)
          killed_spies[country] << spy_hash[:name]
          

          Message.create(player_id: player.id, read: false, 
                       content:"#{spy_hash[:name]} was killed in #{spy_hash[:city]} as the city was destroyed by a nuclear attack",
                       turn_number: game.turn_number)
        
        elsif rand_comparator?(0.1)
          
          game.cities[spy_hash[:city]][:spies].delete(country)
          killed_spies[country] << spy_hash[:name]

          Message.create(player_id: player.id, read: false, 
                       content:"#{spy_hash[:name]} was killed in action by the CIA in #{spy_hash[:city]} without finding Trump",
                       turn_number: game.turn_number)
        end
      end 
    end

    #VICTORY MANAGEMENT ---------------------------------------------------------------------------

    if game.cities[trump_city][:destroyed]
      Player.find(game.cities[trump_city][:destroyed_by][0]).update(winner: true)
      game.status = 'finished'
    
    elsif game.cities[trump_city][:conquered]
      
      players_engaged_firepower = {}
      
      game.players.each do |player|
        player_power = power_computer player.engaged_forces
        players_engaged_firepower[player.country.to_sym] = player_power
      end

      game.players.where(country: players_engaged_firepower.key(players_engaged_firepower.values.max))[0].update(winner: true)
      game.status = 'finished'
    
    elsif game.turn_number == 13 
      game.status = 'finished'
    end

    #GAME AND PLAYERS UPDATES ---------------------------------------------------------------------------

    game.save

    game.players.each do |player| 
      killed_spies[player.country.to_sym].each do |spy_name|
  
        player.spies.select {|k,v| 
          if v[:name] == spy_name
            player.spies[k][:operational] = false
          end 
        }
      end
      
      player.engaged_forces.each do |type, firepower|
        player.engaged_forces[type] = ((1.0 - casualties_caused[:us_army]) * firepower).round
      end 

app/views/games/index.html.erb
<div class='container' id='main-container'>	
	
	
 	<% if current_user.game_invites.empty? && current_user.games.not_finished.empty? %>

		<div class="row justify-content-center content-section">
			<div class="col-md-4 center">
				<%= link_to 'Create a private game', games_path(game: {creator_id: current_user.id, status: "invite_friends"}), 
			method: :post, class: 'btn btn-primary controls' %>
			</div>
			<div class="w-100">
				
			</div>
			<div class="col-md-4 button-hint center">
				3 players are needed to start a game
			</div>
		</div>
		<div class="row justify-content-center content-section">
			<div class="col-md-7">
				<h3 class="section-title">November 2020</h3>
				<p class='center'> Donald Trump lost the election against Mark Zuckerberg in an election impaired by concerns over social media manipulation. </p><p class='danger-text center bold'>The situation is critical.</p> <p class='center'> Trump tweeted that he will “take America hostage with my big nuclear button rather than give away my seat”. He threatened to use the US nuclear arsenal against any country that would not support him by the inauguration on the 21st of January 2021.</p><p class='center content-section'> To prove that he was not kidding, he annihilated North Korea. In the US, two third of the military joined Trump, but one third has started an open rebellion leaded by Zuckerberg, around the New Orleans.</p>
			</div>
		</div>
	<% else %>


		<div class="row justify-content-center content-section">
			<!-- <div class="col-md-4 center">
				<%= link_to 'Join a random game', random_path, method: :post, class: 'btn btn-primary controls' %> 
			</div> -->
			<div class="col-md-4 center">
				<%= link_to 'Create a private game', games_path(game: {creator_id: current_user.id, status: "invite_friends"}), 
					method: :post, class: 'btn btn-primary controls' %>
			</div>
		</div>

		<% if !current_user.game_invites.empty? %>
			<section class="content-section">
				<h3 class='section-title'>Pending invites</h3>

				<table class="table table-hover" id='pending-invites'>
					<%= render 'games/templates/pending_invites_table' %>
				</table>
			</section>
		<% end %>
		<% if !current_user.games.not_finished.empty? %>
			<section class="content-section">
				<h3 class='section-title'>Current games</h3>

				<table class="table table-hover" id='current-games'>
					<%= render 'games/templates/current_games_table' %>
				</table>
			</section>
		<% end %>
	<% end %>
</div>

app/views/games/invite.js.erb
$('#invite-player-<%= params[:invitee_id] %>').css('display', 'none'); 
$('#uninvite-player-<%= params[:invitee_id] %>').css('display', 'inline-block');
$('#invite-player-<%= params[:invitee_id] %>').attr('data-invite', 'true');
$('#uninvite-player-<%= params[:invitee_id] %>').attr('data-uninvite', 'false');

app/views/games/invite_friends.html.erb
<h1>Invite your friends - Status <%= @game.status %></h1>

<table class="table table-hover" id="invite-friends">
	<thead>
		<tr>
			<th class="center"><strong>Username</strong></th>
			<th class="center"><strong>Score</strong></th>
			<th class="center"><strong>Joined at</strong></th>
			<th class="center"><strong>Options</strong></th>

		</tr>
	</thead>
	<tbody>
		<% User.all_except(current_user).each do |invitee| %>
			<tr>
				<td><%= invitee.username %></td>
				<td>TBD</td>
				<td><%= invitee.created_at%></td>
				<td>
					<%= link_to uninvite_path(invitee_id: invitee.id), method: :delete, class: "hidden", 
					id: "uninvite-player-#{invitee.id}" do %>
						<i class="material-icons">close</i>
					<% end %>
					<%= link_to "Invite", invite_path(invitee_id: invitee.id), method: :post, 
					remote: true, class: "btn btn-primary", id: "invite-player-#{invitee.id}" %>
					<script type="text/javascript">
						<% if @game.invitees.include?(invitee) %>
							$('#invite-player-<%= invitee.id %>').css('display', 'none'); 
							$('#uninvite-player-<%= invitee.id %>').css('display', 'inline-block');
						<% end %>
					</script>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<%= link_to 'Launch game', pending_game_path(@game), class: "btn btn-primary" %>

app/views/games/pending_game.html.erb
<h1>Status <%= @game.status %></h1>
<table class="table table-hover">
	<tbody>
		<% @game.players.each do |player| %>		
			<tr>
				<td><%= player.username %></td>
				<td></td>
				<td>country</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/games/uninvite.js.erb
$('#invite-player-<%= params[:invitee_id] %>').css('display', 'inline-block'); 
$('#uninvite-player-<%= params[:invitee_id] %>').css('display', 'none');
$('#invite-player-<%= params[:invitee_id] %>').attr('data-invite', 'false');
$('#uninvite-player-<%= params[:invitee_id] %>').attr('data-uninvite', 'true');