config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  resources :games
  get '/snowboard', to: 'pages#snowboard'
  get 'current_user', to: "games#get_current_user"

  mount ActionCable.server => '/cable'

  post '/games/random', to: 'games#random_game', as: 'random'

  post '/games/:id/invite', to: 'games#invite', as: 'invite'
  delete '/games/:id/uninvite', to: 'games#uninvite', as: 'uninvite'

  post '/games/:id/send_invites', to: 'games#send_invites', as: 'send_invites'
  post '/games/:id/join', to: 'games#join', as: 'join'

  post '/games/:id/actions', to: 'games#actions', as: 'actions'
  delete '/games/:id/cancel_action', to: 'games#cancel_action', as: 'cancel_action'
  post '/games/:id/timer_update', to: 'games#timer_update', as: 'timer_update'
  post '/games/:id/map', to: 'games#map', as: 'map'
  post '/games/:id/get_invite_token', to: 'games#get_invite_token', as: 'get_invite_token'

  post '/read', to: 'messages#read', as: 'read'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord

  belongs_to :creator, class_name: 'User'
  has_many :players, dependent: :destroy
  has_many :users, through: :players
  has_and_belongs_to_many :invitees, class_name: 'User', join_table: 'game_invites_invitees', 
  						  association_foreign_key: 'game_invite_id', foreign_key: 'invitee_id'
  
  serialize :cities
  serialize :us_army_forces
  serialize :rebels_forces
  serialize :launch_sites

  scope :created_by, ->(user) { where(creator_id: user) }
  scope :not_created_by, ->(user) { where.not(creator_id: user) }
  scope :pending, -> { where(status: "pending") }
  scope :ongoing, -> { where(status: "ongoing") }
  scope :not_finished, -> { where.not(status: "finished") }

  def to_param
  	obfuscated_id = Hashids.new("l'art de la guerre", 8)
  	obfuscated_id.encode(id)
  end

end

app/helpers/games_helper.rb
module GamesHelper
  include GameInitializerHelper
  
  TIMER_START = 60

  def create_random_token
    SecureRandom.urlsafe_base64
  end 
  
  def random_game_available?
  	Game.created_by(User.find(1)).pending.empty?
  end

  def join_random_game(user)
  	game = Game.created_by(User.find(1)).pending.first

  	if game.players.where(user_id: user.id).empty?
  		Player.create(game_id: game.id, user_id: user.id, 
                    username: User.find(user.id).username, status:'pending_action')
  	else
  		flash[:danger] = 'You are already part of a random game'
  	end

    ready_to_start?(game)

  	return game
  end

  def create_random_game(user)
  	game = Game.create(creator_id: 1, status: "pending")
  	Player.create(game_id: game.id, user_id: user.id, 
                  username: User.find(user.id).username, status:'pending_action')
  	return game
  end

  def render_partial_for(type)
    statuses = ["invite_friends","pending","ongoing","updated"]
    status = statuses.include?(type) ? type : 'default'
    render "games/templates/#{status}" and return
  end

  def ready_to_start?(game)
    if game.players.size == 3
      game.update(status: "ongoing")
      get_started(game)
    end
  end

  def get_started(game)
    #A nation should be attributed to each player, and the country specific attributes are populated
    countries = [:china, :europe, :russia]
    game.players.shuffle.map.with_index do |player, i|
      player.update(country: countries[i], lost_cities: 0, lost_launch_sites: 0, 
                    launch_sites: LAUNCH_SITES_INITIALIZER[countries[i]], 
                    available_forces: FORCES_INITIALIZER[countries[i]], 
                    engaged_forces: {aircrafts: 0, tanks: 0}, 
                    spies: SPIES_INITIALIZER[countries[i]], 
                    winner: nil,
                    timer: TIMER_START)
    end

    #Trump location is randomized
    trump_location = rand(25)
    puts trump_location
    counter = 0
    cities = CITIES_INITIALIZER

    #cities are initialised and saved as a game attribute
    cities.each do |city, properties|
      if counter == trump_location
        properties[:trump] = true
      else 
        properties[:trump] = false
      end
      properties[:id] = counter
      properties[:spies] = {}
      properties[:destroyed] = false
      properties[:destroyed_by] = []
      properties[:conquered] = false
      counter += 1
    end
    game.update(turn_number: 1, cities: cities, us_army_forces: US_FORCES[:us_army], rebels_forces: REBELS_FORCES[:rebels], launch_sites: US_LAUNCH_SITES[:usa])
  end
  
  def get_missionable_cities(game, player)
    missionable_cities = {}
    game.cities.each do |city,properties|
      if !properties[:destroyed] && !properties[:conquered] && !properties[:spies].include?(player.country)
        missionable_cities[city] = {id: properties[:id]}
      end
    end
    return missionable_cities
  end

  def get_attackable_cities(game)
    attackable_cities = {}
    game.cities.each do |city,properties|
      if !properties[:destroyed] && !properties[:conquered]
        attackable_cities[city] = {id: properties[:id]}
      end
    end

    game.launch_sites.each do |site, properties|
      if properties[:operational]
        attackable_cities[site] = {id: properties[:id]}
      end
    end 
    return attackable_cities
  end 
  
  def reinforcements_for(player)
    reinforcements = {aircrafts: 0, tanks: 0}
    if player.country.to_sym == :europe
      reinforcements[:aircrafts] = FORCES_INITIALIZER[player.country.to_sym][:aircrafts] / 4
      reinforcements[:tanks] = FORCES_INITIALIZER[player.country.to_sym][:tanks] / 4
    else
      reinforcements[:aircrafts] = FORCES_INITIALIZER[player.country.to_sym][:aircrafts] / 6
      reinforcements[:tanks] = FORCES_INITIALIZER[player.country.to_sym][:tanks] / 6
    end
    return reinforcements
  end

  def next_turn(game)

    game.turn_number += 1
    trump_city = ''
    killed_spies = {china: [], europe: [], russia: []}
    
    game.cities.select{ |k,v| 
      if v[:trump]
        trump_city = k
      end
    }

    casualties_caused = {rebels: 0.09, us_army: 0.03}

    #REBELLION MANAGEMENT -------------------------------------------------------------------------
    rebels_power = power_computer game.rebels_forces
    us_army_power = power_computer game.us_army_forces

    game.rebels_forces.each do |type, firepower|
      game.rebels_forces[type] = ((1.0 - casualties_caused[:us_army]) * firepower).round
    end

    game.us_army_forces.each do |type, firepower|
      game.us_army_forces[type] = ((1.0 - casualties_caused[:rebels]) * firepower).round
    end

    possible_conquests = cities_to_be_conquered(game)
    conquered_this_turn = []

    if rebels_power > 0.5 * (rebels_power + us_army_power) && rebels_power <= 0.6 * (rebels_power + us_army_power)
      1.times do 
        conquered = possible_conquests.slice!(0)
        game.cities[conquered][:conquered] = true
        conquered_this_turn << conquered.to_s.humanize.capitalize
      end
    elsif rebels_power > 0.6 * (rebels_power + us_army_power) && rebels_power <= 0.8 * (rebels_power + us_army_power)
      2.times do 
        conquered = possible_conquests.slice!(0)
        game.cities[conquered][:conquered] = true
        conquered_this_turn << conquered.to_s.humanize.capitalize
      end
    elsif rebels_power > 0.8 * (rebels_power + us_army_power) 
      3.times do 
        conquered = possible_conquests.slice!(0)
        game.cities[conquered][:conquered] = true
        conquered_this_turn << conquered.to_s.humanize.capitalize
      end
    end

    if !conquered_this_turn.empty?
      conquered_this_turn = conquered_this_turn.join(', ')

      game.players.each do |player|
        Message.create(player_id: player.id, read: false, 
                       content:"#{conquered_this_turn} were conquered by the rebels and their allies during the last turn",
                       turn_number: game.turn_number)
      end 
    end
    
    #SPIES MANAGEMENT -----------------------------------------------------------------------------
    if !game.cities[trump_city][:spies].empty? && rand_comparator?(0.7)

      game.cities[trump_city][:spies].each do |country, spy_name|
        player = game.players.find_by(country: country)
        if rand_comparator?(0.3)
          
          killed_spies[country] << spy_name
          game.cities[trump_city][:spies].delete(country)

          Message.create(player_id: player.id, read: false, 
                         content:"#{spy_name} was killed after having found Trump in #{trump_city}, and Trump moved to another city",
                         turn_number: game.turn_number)
        else 
          Message.create(player_id: player.id, read: false, 
                         content:"#{spy_name} found Trump in #{trump_city}, but Trump escaped!",
                         turn_number: game.turn_number)
        end

      end

      trump_moves(game)

    elsif game.cities[trump_city][:spies].empty? && game.turn_number % 3 == 1

      trump_moves(game)

    else

      game.cities[trump_city][:spies].each do |country, spy_name|
        player = game.players.find_by(country: country)
        Message.create(player_id: player.id, read: false, 
                       content:"#{spy_name} located Trump in #{trump_city}, don't let him escape!!",
                       turn_number: game.turn_number)
    
      end 

    end

    #SPIES RISK -----------------------------------------------------------------------------------
    
    spies_on_mission = get_spies_on_mission(game)

    spies_on_mission.each do |country, array_of_spies|
      player = game.players.find_by(country: country)
      array_of_spies.each do |spy_hash|
        
        if game.cities[spy_hash[:city]][:destroyed]

          game.cities[spy_hash[:city]][:spies].delete(country)
          killed_spies[country] << spy_hash[:name]
          

          Message.create(player_id: player.id, read: false, 
                       content:"#{spy_hash[:name]} was killed in #{spy_hash[:city]} as the city was destroyed by a nuclear attack",
                       turn_number: game.turn_number)
        
        elsif rand_comparator?(0.1)
          
          game.cities[spy_hash[:city]][:spies].delete(country)
          killed_spies[country] << spy_hash[:name]

          Message.create(player_id: player.id, read: false, 
                       content:"#{spy_hash[:name]} was killed in action by the CIA in #{spy_hash[:city]} without finding Trump",
                       turn_number: game.turn_number)
        end
      end 
    end

    #VICTORY MANAGEMENT ---------------------------------------------------------------------------

    if game.cities[trump_city][:destroyed]
      Player.find(game.cities[trump_city][:destroyed_by][0]).update(winner: true)
      game.status = 'finished'
    
    elsif game.cities[trump_city][:conquered]
      
      players_engaged_firepower = {}
      
      game.players.each do |player|
        player_power = power_computer player.engaged_forces
        players_engaged_firepower[player.country.to_sym] = player_power
      end

      game.players.where(country: players_engaged_firepower.key(players_engaged_firepower.values.max))[0].update(winner: true)
      game.status = 'finished'
    
    elsif game.turn_number == 13 
      game.status = 'finished'
    end

    #GAME AND PLAYERS UPDATES ---------------------------------------------------------------------------

    game.save

    game.players.each do |player| 
      killed_spies[player.country.to_sym].each do |spy_name|
  
        player.spies.select {|k,v| 
          if v[:name] == spy_name
            player.spies[k][:operational] = false
          end 
        }
      end
      
      player.engaged_forces.each do |type, firepower|
        player.engaged_forces[type] = ((1.0 - casualties_caused[:us_army]) * firepower).round
      end 

app/views/games/templates/_current_games_table.html.erb
<thead>
	<tr class='row align-items-center'>
		<th class="center col"><strong>Turn</strong></th>
		<th class="center col"><strong>Status</strong></th>
		<th class="center col"><strong>Created</strong></th>
		<th class="center col"><strong>Actions</strong></th>

	</tr>
</thead>
<tbody>
	<% current_user.games.not_finished.order('created_at DESC').each do |game| %>
		<tr class='row align-items-center'>
			<td class='col'><%= game.turn_number.nil? ? 'Not started' : game.turn_number %></td>
			<td class='col'><%= game.status.humanize %></td>
			<td class='col'><%= game.created_at.strftime('%d %B %y') %></td>
			<td class='col'>
				<%= link_to "Play!", game_path(game), class: "btn btn-primary", 
				data: {game: game.id, status: game.status} %>
				
			</td>
			
		</tr>
	<% end %>
</tbody>

app/views/games/templates/_pending_game_table.html.erb
<div class="content-section top-margin">
	<table class="table table-hover" id='pending-game'>
		<tbody id='current-players'>
			<% @game.players.each do |player| %>		
				<tr>
					<td><%= player.username %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/games/templates/_pending_invites_table.html.erb
<thead>
	<tr class='row align-items-center'>
		<th class="center col"><strong>Creator</strong></th>
		<th class="center col"><strong>Status</strong></th>
		<th class="center col"><strong>Created</strong></th>
		<th class="center col"><strong>Options</strong></th>

	</tr>
</thead>
<tbody>
	<% current_user.game_invites.each do |game| %>	
		<% if game.status == "pending" %>	
			<tr class='row align-items-center'>
				<td class="center col"><%= game.creator.username %></td>
				<td class="center col">Waiting players</td>
				<td class="center col"><%= game.created_at.strftime('%d %B %y') %></td>
				<td class="center col"><%= link_to "Join", join_path(game), method: :post, class: "btn btn-primary", id: "join-game", data:{user: current_user.id } %></td>
			</tr>
		<% end %>
	<% end %>
</tbody>

app/views/games/templates/default.html.erb
<div class='container-fluid' id='main-container'>
	<div class="container full-vertical-center bold">

		<% if @game.players.where(winner: true).empty? %>
			<h3 class='section-title'>Oh no... All players lose...</h3>
			<div class="row center">
				None of the player found and stopped Trump. Earth is doomed to read (and - sometimes - laugh with) Donald Trump's tweets until his death
			</div>
			<div class="row top-margin">
				<iframe src="https://giphy.com/embed/xTiTnHXbRoaZ1B1Mo8" width="480" height="271" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
			</div>
		<% else %>
			<h3 class='section-title'>YAY! <%= @game.players.where(winner: true)[0].country.capitalize %> won!!</h3>
			<div class="row center">
				Thanks to <%= @game.players.where(winner: true)[0].country.capitalize %>'s clever strategy, the world avoided nuclear apocalypse and years of Trump's tweets! 
			</div>
			<div class="row center top-margin">
				<% if @game.cities[get_trump_city(@game)][:destroyed] %>

					<%= @game.players.where(winner: true)[0].country.capitalize %> 
					found Trump in <%= get_trump_city(@game).to_s.humanize.titleize %> and launched a nuclear attack.

				<% elsif @game.cities[get_trump_city(@game)][:conquered] %>
					
					Rebels found Trump in <%= get_trump_city(@game) %> after conquering the city and thanked 
					<%= @game.players.where(winner: true)[0].country.capitalize.to_s.humanize.titleize %> which was their main support in their fight.

				<% end %>
			</div>
			<div class="row top-margin">
				<iframe src="https://giphy.com/embed/ASzK5wWjMtc6A" width="479" height="480" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
			</div>
		<% end %>
		
		<div class="center top-margin">
			<%= link_to 'Back to your games', games_path, class: 'btn btn-primary form-submit' %>
		</div>
		
	</div>
	
</div>

app/views/games/templates/invite_friends.html.erb
<div class='container' id='main-container'>
	<div id="invite-link-section" class="center hidden">
		<strong>Copy this link and share it with your friends: </strong>
		<div class="top-margin form-field" id='invite-link-field'>

		</div> 
		<div class="bold top-margin"> And then... </div>
		<%= link_to 'Get started!', send_invites_path(@game, type: 'invite_link'), method: :post, 
		class: "btn btn-primary top-margin form-submit" %>
	</div>
	<div id="invite-friends-section">
		<div class="center">
			<div class="btn btn-primary top-margin form-submit", id='generate-invite-token'>
				Generate invite link
			</div>	
		</div>
		<div class="top-margin center">
			Or
		</div>
		<h3 class='section-title top-margin'>Invite your friends</h3>

		<table class="table table-hover" id="invite-friends">
			<thead>
				<tr class='row align-items-center'>
					<th class="center col"><strong>Username</strong></th>
					<th class="center col"><strong>President hunter since</strong></th>
					<th class="center col"><strong>Options</strong></th>

				</tr>
			</thead>
			<tbody>
				<% User.all_except(current_user).each do |invitee| %>
					<tr class='row align-items-center'>
						<td class="center col"><%= invitee.username %></td>
						<td class="center col"><%= invitee.created_at.strftime('%d %B %y') %></td>
						<td class="center col">
							<%= link_to uninvite_path(invitee_id: invitee.id), method: :delete, class: "hidden", 
							id: "uninvite-player-#{invitee.id}", data: {user: invitee.id, uninvite:"true"} do %>
								<i class="material-icons">close</i>
							<% end %>
							<%= link_to "Invite", invite_path(invitee_id: invitee.id), method: :post, 
							remote: true, class: "btn btn-primary", id: "invite-player-#{invitee.id}", 
							data: {user: invitee.id, invite:"false"} %>
							<script type="text/javascript">
								<% if @game.invitees.include?(invitee) %>
									$('#invite-player-<%= invitee.id %>').css('display', 'none'); 
									$('#uninvite-player-<%= invitee.id %>').css('display', 'inline-block');
								<% end %>
							</script>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
		<div class="center">
			<%= link_to 'Send invites', send_invites_path(@game), method: :post, 
			class: "btn btn-primary top-margin form-submit", id: 'send-invites', data: {game: @game.id} %>
		</div>
	</div>
</div>

app/views/games/templates/ongoing.html.erb
<% if current_user.show_tutorial %>
  <script type="text/javascript">
    
  </script>
<% end %>
<div class='container-fluid' id='main-container'>
  <form action=<%= game_path(@game)%> method="post" class='cities-form' id='cities-form'>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
    <input name="_method" type="hidden" value="patch" />
    <div class="row align-items-center" data-game='<%= @game.id %>' id='game-header'>
      <div class="col-md-4">
        <div class="row align-items-center justify-content-center">
          <div class="col center">
          <% if @player.country == 'china' %> 
            <%= image_tag('china.svg', size: '36x36', class: 'right-margin-sm') %>
          <% elsif @player.country == 'europe' %>
            <%= image_tag('european-union.svg', size: '36x36', class: 'right-margin-sm') %>
          <% elsif @player.country == 'russia' %>
            <%= image_tag('russia.svg', size: '36x36', class: 'right-margin-sm') %>
          <% end %>
          
            <strong><%= @player.country.capitalize %></strong>
          </div>
        </div>
        <div class="row align-items-baseline justify-content-center">
          <div class="col header bold center">
            <span class='bold right-margin-md'>Week <%= @game.turn_number %></span>
            <span class='bold right-margin-md'>-</span>
            <span id='timer' class='danger-text bold'><%= @player.timer %></span> seconds left
          </div>
          <script type="text/javascript">
            //startTimer(); 
          </script>
        </div>
      
        <div class="row">
          <div class="col center">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-action-selection" id='action-selection'>
              Available actions
            </button>

            <input type="submit" value="Update" name="commit" 
            class="btn btn-primary hidden" id='cities-submit' disabled />

            <%= link_to 'Cancel action', cancel_action_path(@game), method: :delete, 
            class: "btn btn-danger hidden", id:'action-cancel' %>
          </div>
          
        </div>
      </div>
      <div class="col-md-6">
        <div class="container game-info">
          <div class="row">
            <div class="bold col-md-2 vertical-center">
              Rebels
            </div>
            <div class='col-md-4'>
              <% @game.rebels_forces.each do |type, number| %>
                <div class="row">
                  <div class="col-6"><%= type.capitalize %></div>
                  <div class="col-6"><%= number %></div>
                </div>  
              <% end %>
            </div>
            <div class="bold col-md-2 vertical-center">
              US Army
            </div>
            <div class='col-md-4'>
              <% @game.us_army_forces.each do |type, number| %>
                <div class="row">
                  <div class="col-6"><%= type.capitalize %></div>
                  <div class="col-6"><%= number %></div>
                </div>  
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-2">
        <div id="message-button">
          <i class="material-icons md-28" id='message-icon'>message</i>
          <div id="unread-counter"></div>
        </div>
        <div id="message-button-close">
          <i class="material-icons md-36" id='message-icon'>keyboard_arrow_up</i>
          <div id="unread-counter-close"></div>
        </div>
        <div id="message-container">
          <div class="container-fluid message-dialog">
          <% if @player.messages.empty? %>
            <div class="message">
              <div class="message-content">
                You will receive messages to inform you about your spies findings, other players actions, and cities conquered by the rebels
              </div>
            </div>

          <% else %>
            <% @player.messages.order('created_at DESC').each do |message| %>
              <div class="message">
                <div class="message-info spaced">
                  
                  <div class="bold">Week <%= message.turn_number %></div>
                  <i class="material-icons md-18 <%= message.read ? 'read' : 'unread' %>" 
                     data-message='<%= message.id %>'>
                   remove_red_eye
                  </i>
                </div>
                <div class="message-content">
                  <%= message.content %>
                </div>
              </div>
            <% end %>
          <% end %>
          </div>  
        </div>
      </div>

    </div>
    <div class="row">
      <div class="col-md-8">
        <div id='map' >
          <div class='map-overlay container'>
            <div class="row align-items-center">
              <div class="col-2"><i class="material-icons md-18 location-input active">account_balance</i></div>
              <div class="col-10">City</div>
            </div>
            <div class="row align-items-center">
              <div class="col-2"><i class="material-icons md-18 location-input active">gps_fixed</i></div>
              <div class="col-10">US Launch Site</div>
            </div>
            <div class="row align-items-center">
              <div class="col-2"><i class="material-icons md-18 location-input destroyed">flag</i></div>
              <div class="col-10">Conquered by rebels</div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="player-info" id="general">
          <div class="row">
            <div class="col-md-12 spaced">
              <div class="bold">
                Playing: <%= @player.country.capitalize %>    
              </div>
              <div>
                <%= @player.lost_cities %> / <%= (@player.country == 'china') ? 9 : 5 %>  cities lost
              </div>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="bold col-md-3 vertical-center">
              Launch sites
            </div>
            <div class='col-md-9'>
              <% @player.launch_sites.each do |name, attributes| %>
              <div class="row">
                <div class='col'>
                  <%= name.capitalize %>
                </div> 
                <div class='col'>
                  <%= attributes[:operational] ? 'Operational' : 'Destroyed' %>
                </div>         
              </div>
              <% end %>
            </div>  
          </div>
        </div>
        <div class="player-info" id="spies">
          <div class="row">
            <div class="bold col-md-3 vertical-center">
              Spies
            </div>
            <div class='col-md-9'>
            <% @player.spies.each do |id, attributes| %>
              <div class="row">
                <div class='col'>
                  <%= attributes[:name] %>              
                </div>
                <div class='col'>
                  <%= attributes[:operational] ? 'Operational' : 'Killed in action' %>
                </div>
              </div>
              
            <% end %>
            </div>
          </div>
        </div>
        <div class="player-info" id="available-forces">
          <div class="row">
            <div class="bold col-md-3 vertical-center">
              Available forces
            </div>
            <div class='col-md-9'>
            <% @player.available_forces.each do |type, number| %>
              <div class="row">
                <div class="col"><%= type.capitalize %></div>
                <div class="col"><%= number %></div>
              </div>  
            <% end %>
            </div>
          </div>
        </div>
        <div class="player-info" id="engaged-forces">
          <div class="row">
            <div class="bold col-md-3 vertical-center">Engaged forces</div>
            <div class='col-md-9'>
            <% @player.engaged_forces.each do |type, number| %>
              <div class="row">
                <div class='col'><%= type.capitalize %></div>
                <div class='col'><%= number %></div>
              </div>
            <% end %>
            </div>
          </div>
        </div>
      </div>


      
    </div>
  </form>
  <div class="modal fade" id="modal-action-selection">
    <div class="modal-dialog" id='modal-action-dialog'>
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
          <h3 class="modal-title">What will you do, <%= @player.country.capitalize %>?</h3>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
            <!-- Modal body -->
        <div class="modal-body" id='modal-form'>
          <div id="modal-actions">
            <div class="container-fluid">
              <div class="row button-row">
                <div class="col-sm-7">
                  <button type="button" class="btn btn-primary" data-action="recruit">
                    Recruit a new spy
                  </button>
                </div>
                <div class="col-sm-5 hint">
                  A new spy will be available next turn.
                </div>
              </div>
              <div class="row button-row">
                <div class="col-sm-7">
                  <button type="button" class="btn btn-primary" data-action="mission">
                    Change spies location
                  </button>
                </div>
                <div class="col-sm-5 hint">
                  If placed in a city, a spy will inform you if Trump is here, but might be killed in action.
                </div>
              </div>
              <div class="row button-row">
                <div class="col-sm-7">
                  <button type="button" class="btn btn-primary" data-action="attack" 
                          <%= can_attack?(@player.launch_sites) ? nil : 'disabled' %>>
                    Launch a nuclear attack
                  </button>
                </div>
                <div class="col-sm-5 hint">
                  A city/launch site will be destroyed and Trump killed if the right city is targeted. Beware, Trump will retaliate as long as US have launch sites. 
                </div>
              </div>
              <div class="row button-row">
                <div class="col-sm-7">
                  <button type="button" class="btn btn-primary" data-action="reinforce"
                          <%= can_reinforce?(@player.available_forces) ? nil : 'disabled' %>>
                    Send reinforcements to rebels
                  </button>
                </div>
                <div class="col-sm-5 hint">
                  As their forces grow, rebels will conquer cities. If Trump is in a conquered city, the player with the largest engaged forces wins.
                </div>
              </div>
            </div>
          </div>
          <div id="modal-update" class='hidden'>
            <form action=<%= game_path(@game)%> method="post" class='modal-form'>
              <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
              <input name="_method" type="hidden" value="patch" />

            </form>
            <div class="alert alert-info-inverted hidden top-margin" id="modal-notification-area">
    
            </div>
          </div>
        </div>
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger center" data-dismiss="modal" id='modal-dismissal'>
            Back to map
          </button>
          <%= link_to 'Cancel action', cancel_action_path(@game), method: :delete, 
          class: "btn btn-danger hidden", id:'modal-action-cancel' %>
        </div>   
      </div>    
    </div>
  </div>
</div>

app/views/games/templates/pending.html.erb
<div class='container' id='main-container'>	
	<div class="container" data-game='<%= @game.id %>'>

		<p class="center content-section">
			The world's main powers have <strong> 12 weeks until the 21st Jan 2021 </strong>to thwart Trump's nefarious plans and prevent the advent of an era of terror. <br> Your mission is to find him and put him out of business.
		</p>

		<div class="center top-margin content-section">
			<button class="btn btn-primary" id="get-started" disabled="<%= @game.players.size == 3 ? true : nil %>">Let's get started! </button>
			<div class="button-hint center">3 players needed</div>
		</div>
		
	
		<h3 class="section-title">Special powers</h3>
		<div class="row top-margin">
			<div class="col-sm-4 bold">China - Emerging nuclear power</div> 
			<div class="col-sm-8">China starts with 5 launch sites, can lose 9 cities instead of 5</div>
		</div>
		<div class="row top-margin">
			<div class="col-sm-4 bold">Europe - Modern military</div> 
			<div class="col-sm-8">Europe can send 1/4 of its army in reinforcement per turn instead of 1/6</div>
		</div>
		<div class="row top-margin content-section">
			<div class="col-sm-4 bold">Russia - KGB networks</div> 
			<div class="col-sm-8">Russia starts with 3 spies instead of 2</div>
		</div>

		
	</div>
	<div class="container">
		<h3 class="section-title">Players</h3>
		<%= render 'games/templates/pending_game_table' %>
	</div>	
</div>